services:
  db:
    image: postgres:16-alpine
    container_name: aurora_erp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: aurora_erp
    ports:
      - "5432:5432"
    volumes:
      - aurora_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: aurora_erp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aurora.ac.in
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  aurora_pgdata:
