export { api } from "./axios.instance";
export { authApi } from "./auth.api";
export { usersApi } from "./users.api";
export { academicApi } from "./academic.api";
export { attendanceApi } from "./attendance.api";
export { assignmentsApi } from "./assignments.api";
export { analyticsApi } from "./analytics.api";
export { noticeboardApi } from "./noticeboard.api";
export { searchApi } from "./search.api";
